### ISSUE TITLE
2ое задание Oh my var

### ISSUE THREAD

**Issue by philatm** [hexlet-basics/exercises-php#1]
![screenshot-2017-12-19 http code-basics ru](https://user-images.githubusercontent.com/10869388/34172155-e597f1a0-e512-11e7-8606-15da82d26ab9.png)
Где дается пример вывода, не видно кода. По умолчанию у блока pre значение color = #fffffb

**Comment by mokevnin** [comment]
@freetonik глянь плс

**Comment by freetonik** [comment]
Поправил, спасибо. Ждем деплоя.
