### ISSUE TITLE
Арифметика 8/75 - оператор это не "символ"

### ISSUE THREAD

**Issue by sergey-nechaev** [hexlet-basics/exercises-php#143]
https://ru.code-basics.com/languages/php/modules/arithmetics/lessons/operator

>Оператор — просто символ, который производит некоторую операцию

С большой натяжкой. Например, `instanceof` уже не назвать символом. Если пример попроще, то `**`, `!==`.

https://www.php.net/manual/ru/language.operators.php
https://www.php.net/manual/ru/language.operators.type.php

**Comment by mokevnin** [comment]
Да спасибо, я поправил теорию, щас зальем)

**Comment by sergey-nechaev** [comment]
Английский ещё остался - https://github.com/hexlet-basics/exercises-php/blob/master/modules/20-arithmetics/25-operator/description.en.yml#L6
