### ISSUE TITLE
`make compose-test` не работает

### ISSUE THREAD

**Issue by sergey-nechaev** [hexlet-basics/exercises-php#154]
В какой-то момент из `Makefile` пропало правило `compose-test`. Я полагаю, что должно быть так:

```makefile
compose-test:
	docker-compose run exercises make test
```

**Comment by mokevnin** [comment]
ага, можно отсюда брать https://github.com/hexlet-basics/exercises-javascript/blob/master/Makefile

Сможете сделать пулреквест?
