### ISSUE TITLE
php 70/76

### ISSUE THREAD

**Issue by TolokonnikovNV** [hexlet-basics/exercises-php#170]
В редакторе выше // BEGIN уже прописано название функции и аргумент который она принимает. В предыдущих заданиях было необходимо самостоятельно ее создать.

**Comment by ashikov** [comment]
Приветствую!

Спасибо за фидбек! Когда `// BEGIN` располагается внутри функции, её предлагается дописать. Я пробежался по всем упражнениям и изменил формулировки там, где это было необходимо.
