### ISSUE TITLE
Кавычки 13/82 — обратный слеш перед обычным символом

### ISSUE THREAD

**Issue by konfuji** [hexlet-basics/exercises-php#263]
https://github.com/hexlet-basics/exercises-php/blob/53460a8d19f203959de15bb1c0a94f7d04e26b04/modules/25-strings/10-quotes/description.ru.yml#L76-L79

Возможно, что-то не так понял, но если это не управляющая последовательность, то `/` выводится: https://3v4l.org/eOLfc
[Документация](https://www.php.net/manual/ru/language.types.string.php#language.types.string.syntax.double:~:text=%D0%9A%D0%B0%D0%BA%20%D0%B8%20%D0%B2%20%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B5%2C%20%D0%B7%D0%B0%D0%BA%D0%BB%D1%8E%D1%87%D1%91%D0%BD%D0%BD%D0%BE%D0%B9%20%D0%B2,%D0%B2%D1%8B%D0%B2%D0%B5%D0%B4%D0%B5%D1%82%20%D1%82%D0%B0%D0%BA%D0%B6%D0%B5%20%D0%B8%20%D1%81%D0%B0%D0%BC%20%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F.)

**Comment by zhabinka** [comment]
https://github.com/hexlet-basics/exercises-php/commit/8f665de3012b09193d3f6e4fa97b4e522bce41ac
