### ISSUE TITLE
НЕ принимает решение в задании 68

### ISSUE THREAD

**Issue by bumerangman** [hexlet-basics/exercises-php#289]
<?php

namespace HexletBasics\Loops\IterationOverString;

// BEGIN (write your solution here)
function printReversedNameBySymbol($name) {
    $i = -1;
    while (abs($i) <= strlen($name) {
        print_r("$name[$i]\n");
        $i = $i - 1;
    }
}
// END

**Comment by fey** [comment]
Добрый день, пожалуйста, пришлите код, который не проходит решение.
