### ISSUE TITLE
Недопонимания в 29/74 Heredoc

### ISSUE THREAD

**Issue by Orkevich** [hexlet-basics/exercises-php#49]
В задании написано "перед EOD не должно стоять пробелов" и сам текст, который требуется для ввода имеет пробелы и обучающий пример имеет пробелы перед текстом. Но при этом "Решения учителя" не имеет пробелов перед абзацами текста и в связи с этим моё решение задания он считает неверным.

![1 1](https://user-images.githubusercontent.com/46517585/50967763-86ef9480-14f2-11e9-9a70-a426e701cebe.jpg)

![2](https://user-images.githubusercontent.com/46517585/50967505-c1a4fd00-14f1-11e9-996b-5246e7d263eb.jpg)
![3](https://user-images.githubusercontent.com/46517585/50967507-c23d9380-14f1-11e9-92ce-7704cd911948.jpg)
![4](https://user-images.githubusercontent.com/46517585/50967508-c23d9380-14f1-11e9-808c-bbfc9dd48271.jpg)
![5](https://user-images.githubusercontent.com/46517585/50967509-c23d9380-14f1-11e9-8645-80a9aa1f9f5c.jpg)
![6](https://user-images.githubusercontent.com/46517585/50967510-c2d62a00-14f1-11e9-86ea-9f8a3c54a109.jpg)

**Comment by mokevnin** [comment]
Спасибо, поправил. Скоро залью.
