### ISSUE TITLE
54/74 Логика - else. Не принимает любое решение.

### ISSUE THREAD

**Issue by Orkevich** [hexlet-basics/exercises-php#54]
Выписывал самые разные решения: через функцию substr и через strpos, и через ELSE(по образу в примере) и без него, испробовал разные оформления кода, даже прождал пол часа чтобы получить решение, которое оказалось почти идентичным моему[*]. Но даже скопипастив "Решение учителя" консоль всё равно выдавала мне отказ[**]. Это как так?

[*] https://pp.userapi.com/c851128/v851128519/8bb3f/cAl5LRQxGzM.jpg

[**] https://pp.userapi.com/c848632/v848632524/f7ec0/znuILHk64Ro.jpg

PS: В самом уроке нет ни слова о применении true/false в самом коде.

**Comment by mokevnin** [comment]
Это скорее старое решение, мы его заменили.
