### ISSUE TITLE
php  Определение функций 47/76

### ISSUE THREAD

**Issue by gittsk** [hexlet-basics/exercises-php#62]
Код прошел, а не должен...

<?php

// BEGIN
function getAgeDifference ($number) {
    $number = 'number';
    $a = 'The age difference is' . $number;
    return print_r($a);
}

// END

output: The age difference isnumber1

**Comment by mokevnin** [comment]
Было бы хорошо увидеть какой код не прошел и почему не должен. Иначе непонятно что с этой информацией делать)

**Comment by gittsk** [comment]
Пардон, я по памяти воссоздал свой гавнокод.

Решение учителя:

<?php
// BEGINfunction getAgeDifference($yearOne, $yearTwo){
    $difference = abs($yearOne - $yearTwo);
    return "The age difference is {$difference}";
}// END

Ваше решение:

<?php
// BEGIN
function getAgeDifference($age1, $age2){
    $result = $age1 - $age2;
    return print_r("The age difference is " . $result);
}

// END

The age difference is -171


Между тем, решение учителя The age difference is 17

Мне показалось любопытным сие. Спасибо за потраченное время!

сб, 2 мар. 2019 г. в 22:35, Mokevnin Kirill <notifications@github.com>:
