### ISSUE TITLE
сокращенная форма записи if else if для модернизированного задания. Урок 56. 

### ISSUE THREAD

**Issue by baikal911** [hexlet-basics/exercises-php#68]
https://code-basics.ru/languages/php/modules/logic/lessons/if-else#comment-4376333410
Модернизация такая (делаем как в предыдущем уроке):
Вместо:
Функция принимает адреса в виде
АДРЕС или http://АДРЕС,
но всегда возвращает адрес в виде https://АДРЕС
Так:
Функция принимает адреса в виде
АДРЕС или http://АДРЕС или https://АДРЕС,
но всегда возвращает адрес в виде https://АДРЕС.
"Классический" вариант if-elseif-else - без проблем.
В сокращенной форме записи при наличии "s" в https - получаем ТРОЙНОЙ слеш!

function normalizeUrl($url) {
    return strpos($url, 'https:') === 0 ? $url :
    strpos($url, 'http:') === 0 ? 'https://' . substr($url, 7) :
    'https://' . $url;
}
$norm5 = normalizeUrl('https://domain-name.com');
print_r('$norm5 ' . $norm5); 

//$norm5 https:///domain-name.com
"ПААЧИИМУУУ!" ))

**Comment by baikal911** [comment]
//$norm5 https:///domain-name.com

**Comment by zhabinka** [comment]
У тернарного оператора в PHP есть особенности поведение. Небольшая статья на эту тему - https://habr.com/ru/post/114899/. Нужно явно задать порядок выполнения с помощью скобок.

**Comment by baikal911** [comment]
Спасибо!

**Comment by baikal911** [comment]
Решено.
