### ISSUE TITLE
Урок 31, Heredoc, не верно работает подсветка кода

### ISSUE THREAD

**Issue by Lexx918** [hexlet-basics/exercises-php#82]
Одинарные кавычки внутри Heredoc-строки парсятся как границы литерала и подсветка кода разваливается от первой кавычки до конца исходника задания.

**Comment by mokevnin** [comment]
Кажись починилось)

**Comment by sergey-nechaev** [comment]
@mokevnin 
Не, речь о подсветке в редакторе:

![image](https://user-images.githubusercontent.com/3796512/77611913-72a58500-6f48-11ea-8155-b02e9c40ca2a.png)

Двойные кавычки тоже, кстати, ожидают закрытия для правильной подсветки.

Но это получатеся баг `monaco` и вообще относится к https://github.com/hexlet-basics/hexlet_basics
