### ISSUE TITLE
Задание придумать название переменной отсутствует

### ISSUE THREAD

**Issue by burenkov-anton** [hexlet-basics/exercises-php#94]
Данное задание есть в курсе по javascript, но не по php - https://code-basics.ru/languages/javascript/modules/variables/lessons/naming

![phpVarNameIssue](https://user-images.githubusercontent.com/11513918/61209266-74fde100-a723-11e9-8d3c-781bbb88949f.png)

**Comment by zhabinka** [comment]
Нужно:
- либо расширить урок про именование переменных - https://ru.code-basics.com/languages/php/modules/variables/lessons/naming
- либо выпилить 2 абзаца из урока про именование функций - https://ru.code-basics.com/languages/php/modules/define-functions/lessons/naming

@mokevnin, как поступим?
